# Generated by Django 3.0.5 on 2020-05-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('private', 'Private')], default='publish', max_length=129),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Post Title'),
        ),
    ]
