# Generated by Django 3.0.5 on 2020-05-08 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogModel', '0003_auto_20200508_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 17, 8, 42, 414894, tzinfo=utc)),
        ),
    ]
