# Generated by Django 3.0.5 on 2020-05-08 17:24

import blogModel.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogModel', '0005_auto_20200508_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[blogModel.validator.valid_mehedi]),
        ),
    ]
