# Generated by Django 2.2 on 2020-05-21 17:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogModel', '0008_auto_20200508_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postmodel',
            managers=[
                ('other', django.db.models.manager.Manager()),
            ],
        ),
    ]
